Script started on Fri 06 Nov 2015 10:13:48 PM PST
[fyang016@hammer assn1]$ bin/rshell
fyang016@hammer.cs.ucr.edu$ exit
[fyang016@hammer assn1]$ bin/rshell
fyang016@hammer.cs.ucr.edu$ exit || exit
[fyang016@hammer assn1]$ bin/rshell
fyang016@hammer.cs.ucr.edu$ exit && exit
[fyang016@hammer assn1]$ bin/rshell
fyang016@hammer.cs.ucr.edu$ exit && ls
[fyang016@hammer assn1]$ bin/rshell
fyang016@hammer.cs.ucr.edu$ exit || ls
[fyang016@hammer assn1]$ bin/rshell
fyang016@hammer.cs.ucr.edu$ exit #exit
[fyang016@hammer assn1]$ exit
exit

Script done on Fri 06 Nov 2015 10:14:24 PM PST
